on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  pnpm-version: '8'

name: CheckSpell
jobs:
  lint:
    name: CheckSpell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}
      - uses: actions/setup-node@v3.7.0
      - run: pnpm install
      - run: pnpm cSpell
